### ISSUE TITLE
[iOS] Unable to Close (Cancel) the payment.

### ISSUE THREAD

**Issue by SebghatYusuf** [Flutterwave/Flutter-v3#38]
### Description
Unable to cancel (Close the checkout screen on iOS). 

### Steps to Reproduce

1. Add flutterwave_standard to your flutter app. 
2. Configure it to be able to open the Flutterwave checkout page
3.Open the flutter app on an iPhone or iOS simulator. 
4. will not be able to close the payment checkout page (screen). 

Here's a screenshot. 
![simulator_screenshot_A9DFD93E-100C-4877-AA84-DDEA1B855BA6](https://user-images.githubusercontent.com/48417629/206850435-1c4e66e1-a57a-4098-a87a-fa1c3921a889.png)

**Expected behaviour:**
Should be able to cancel without having to close the app. 

**Actual behaviour:**
Now it's not allowing to close the payment sheet. 

**Reproduces how often:**
100% (anytime in iOS). 

### Configuration

- Environment: Test mode and live mode. 
- Language: Dart

**Comment by abwmcoders** [comment]
Experiencing same issues with flutterwave standard package.

**Comment by Abdulah-butt** [comment]
facing the same issue in IOS, did anyone find solution?

**Comment by Oyedee** [comment]
Facing same issue on iOS. The cancel button does not close the in app payment webview.

**Comment by HenryEffiong** [comment]
Same issue on iOS too. Any fix yet?

**Comment by FredDominant** [comment]
Closing this as it is confirmed fixed.
